// Input 0
var v;
window.overlayTerminal=function(a){a=a?a.split("&"):location.search.substr(1).split("&");if(0!=a.length){for(var b={},c=0;c<a.length;c++){var d=a[c].indexOf("=");0>d&&(b[a[c]]=1);0<d&&(b[a[c].substring(0,d)]=a[c].substring(d+1))}b.name||(b.name=a[0]);b.title||(b.title=a[0].length?null:"");b.autostart||(b.autostart=1E3);b.warp||(b.warp=1);b.scan||(b.scan=!1);b.noskip||(b.noskip=!1);a[0].length?(b.font||b.fontsize||(b.fontsize=13),b.fontfamily||b.font||(b.font="fixed-8x13",b.boldfont="fixed-8x13B"),0==
b.fontsize&&(b.fontsize=null)):b.fontfamily||b.font||(b.font="c64",b.fontfamily="c64");b.controls=b.controls?parseInt(b.controls,10):a[0].length;new aa(b);return!1}};window.startDemo=function(){var a={debug:!1,scan:!1,autostart:1E3,warp:1,font:"c64",title:"",loop:1E3,controls:0,onclose:function(){a.loop=0}},b=document.getElementById("frame"),c=new da(a);b.appendChild(c);return!1};
// Input 1
var y=y||function(a,b){function c(){}var d={},e=d.fa={},f=e.ab={extend:function(a){c.prototype=this;var b=new c;a&&b.Ta(a);b.hasOwnProperty("init")||(b.I=function(){b.Ub.I.apply(this,arguments)});b.I.prototype=b;b.Ub=this;return b},create:function(){var a=this.extend();a.I.apply(a,arguments);return a},I:function(){},Ta:function(a){for(var b in a)a.hasOwnProperty(b)&&(this[b]=a[b]);a.hasOwnProperty("toString")&&(this.toString=a.toString)},W:function(){return this.I.prototype.extend(this)}},k=e.qa=
f.extend({I:function(a,c){a=this.G=a||[];this.D=c!=b?c:4*a.length},toString:function(a){return(a||h).stringify(this)},concat:function(a){var b=this.G,c=a.G,d=this.D;a=a.D;this.sb();if(d%4)for(var e=0;e<a;e++)b[d+e>>>2]|=(c[e>>>2]>>>24-e%4*8&255)<<24-(d+e)%4*8;else if(65535<c.length)for(e=0;e<a;e+=4)b[d+e>>>2]=c[e>>>2];else b.push.apply(b,c);this.D+=a;return this},sb:function(){var b=this.G,c=this.D;b[c>>>2]&=4294967295<<32-c%4*8;b.length=a.ceil(c/4)},W:function(){var a=f.W.call(this);a.G=this.G.slice(0);
return a},random:function(b){for(var c=[],d=0;d<b;d+=4)c.push(4294967296*a.random()|0);return new k.I(c,b)}}),g=d.ja={},h=g.Ic={stringify:function(a){var b=a.G;a=a.D;for(var c=[],d=0;d<a;d++){var e=b[d>>>2]>>>24-d%4*8&255;c.push((e>>>4).toString(16));c.push((e&15).toString(16))}return c.join("")},parse:function(a){for(var b=a.length,c=[],d=0;d<b;d+=2)c[d>>>3]|=parseInt(a.substr(d,2),16)<<24-d%8*4;return new k.I(c,b/2)}},r=g.eb={stringify:function(a){var b=a.G;a=a.D;for(var c=[],d=0;d<a;d++)c.push(String.fromCharCode(b[d>>>
2]>>>24-d%4*8&255));return c.join("")},parse:function(a){for(var b=a.length,c=[],d=0;d<b;d++)c[d>>>2]|=(a.charCodeAt(d)&255)<<24-d%4*8;return new k.I(c,b)}},s=g.Oc={stringify:function(a){try{return decodeURIComponent(escape(r.stringify(a)))}catch(b){throw Error("Malformed UTF-8 data");}},parse:function(a){return r.parse(unescape(encodeURIComponent(a)))}},u=e.Wb=f.extend({reset:function(){this.aa=new k.I;this.Ja=0},ra:function(a){"string"==typeof a&&(a=s.parse(a));this.aa.concat(a);this.Ja+=a.D},ba:function(b){var c=
this.aa,d=c.G,e=c.D,f=this.V,h=e/(4*f),h=b?a.ceil(h):a.max((h|0)-this.lb,0);b=h*f;e=a.min(4*b,e);if(b){for(var s=0;s<b;s+=f)this.ib(d,s);s=d.splice(0,b);c.D-=e}return new k.I(s,e)},W:function(){var a=f.W.call(this);a.aa=this.aa.W();return a},lb:0});e.$b=u.extend({F:f.extend(),I:function(a){this.F=this.F.extend(a);this.reset()},reset:function(){u.reset.call(this);this.Ia()},update:function(a){this.ra(a);this.ba();return this},Z:function(a){a&&this.ra(a);return this.sa()},V:16,Ha:function(a){return function(b,
c){return(new a.I(c)).Z(b)}},cc:function(a){return function(b,c){return(new q.Hc.I(a,c)).Z(b)}}});var q=d.ua={};return d}(Math);
(function(){var a=y.fa.qa;y.ja.bb={stringify:function(a){var c=a.G,d=a.D,e=this.kb;a.sb();a=[];for(var f=0;f<d;f+=3)for(var k=(c[f>>>2]>>>24-f%4*8&255)<<16|(c[f+1>>>2]>>>24-(f+1)%4*8&255)<<8|c[f+2>>>2]>>>24-(f+2)%4*8&255,g=0;4>g&&f+0.75*g<d;g++)a.push(e.charAt(k>>>6*(3-g)&63));if(c=e.charAt(64))for(;a.length%4;)a.push(c);return a.join("")},parse:function(b){var c=b.length,d=this.kb,e=d.charAt(64);e&&(e=b.indexOf(e),-1!=e&&(c=e));for(var e=[],f=0,k=0;k<c;k++)k%4&&(e[f>>>2]|=(d.indexOf(b.charAt(k-1))<<
k%4*2|d.indexOf(b.charAt(k))>>>6-k%4*2)<<24-f%4*8,f++);return a.create(e,f)},kb:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="}})();
(function(a){function b(a,b,c,d,e,t,f){a=a+(b&c|~b&d)+e+f;return(a<<t|a>>>32-t)+b}function c(a,b,c,d,e,t,f){a=a+(b&d|c&~d)+e+f;return(a<<t|a>>>32-t)+b}function d(a,b,c,d,e,t,f){a=a+(b^c^d)+e+f;return(a<<t|a>>>32-t)+b}function e(a,b,c,d,e,t,f){a=a+(c^(b|~d))+e+f;return(a<<t|a>>>32-t)+b}for(var f=y.fa,k=f.qa,g=f.$b,f=y.ua,h=[],r=0;64>r;r++)h[r]=4294967296*a.abs(a.sin(r+1))|0;f=f.fb=g.extend({Ia:function(){this.ta=new k.I([1732584193,4023233417,2562383102,271733878])},ib:function(a,f){for(var q=0;16>
q;q++){var g=f+q,k=a[g];a[g]=(k<<8|k>>>24)&16711935|(k<<24|k>>>8)&4278255360}var q=this.ta.G,g=a[f+0],k=a[f+1],t=a[f+2],x=a[f+3],r=a[f+4],G=a[f+5],I=a[f+6],z=a[f+7],K=a[f+8],M=a[f+9],O=a[f+10],T=a[f+11],C=a[f+12],X=a[f+13],ba=a[f+14],ca=a[f+15],n=q[0],p=q[1],l=q[2],m=q[3],n=b(n,p,l,m,g,7,h[0]),m=b(m,n,p,l,k,12,h[1]),l=b(l,m,n,p,t,17,h[2]),p=b(p,l,m,n,x,22,h[3]),n=b(n,p,l,m,r,7,h[4]),m=b(m,n,p,l,G,12,h[5]),l=b(l,m,n,p,I,17,h[6]),p=b(p,l,m,n,z,22,h[7]),n=b(n,p,l,m,K,7,h[8]),m=b(m,n,p,l,M,12,h[9]),l=
b(l,m,n,p,O,17,h[10]),p=b(p,l,m,n,T,22,h[11]),n=b(n,p,l,m,C,7,h[12]),m=b(m,n,p,l,X,12,h[13]),l=b(l,m,n,p,ba,17,h[14]),p=b(p,l,m,n,ca,22,h[15]),n=c(n,p,l,m,k,5,h[16]),m=c(m,n,p,l,I,9,h[17]),l=c(l,m,n,p,T,14,h[18]),p=c(p,l,m,n,g,20,h[19]),n=c(n,p,l,m,G,5,h[20]),m=c(m,n,p,l,O,9,h[21]),l=c(l,m,n,p,ca,14,h[22]),p=c(p,l,m,n,r,20,h[23]),n=c(n,p,l,m,M,5,h[24]),m=c(m,n,p,l,ba,9,h[25]),l=c(l,m,n,p,x,14,h[26]),p=c(p,l,m,n,K,20,h[27]),n=c(n,p,l,m,X,5,h[28]),m=c(m,n,p,l,t,9,h[29]),l=c(l,m,n,p,z,14,h[30]),p=c(p,
l,m,n,C,20,h[31]),n=d(n,p,l,m,G,4,h[32]),m=d(m,n,p,l,K,11,h[33]),l=d(l,m,n,p,T,16,h[34]),p=d(p,l,m,n,ba,23,h[35]),n=d(n,p,l,m,k,4,h[36]),m=d(m,n,p,l,r,11,h[37]),l=d(l,m,n,p,z,16,h[38]),p=d(p,l,m,n,O,23,h[39]),n=d(n,p,l,m,X,4,h[40]),m=d(m,n,p,l,g,11,h[41]),l=d(l,m,n,p,x,16,h[42]),p=d(p,l,m,n,I,23,h[43]),n=d(n,p,l,m,M,4,h[44]),m=d(m,n,p,l,C,11,h[45]),l=d(l,m,n,p,ca,16,h[46]),p=d(p,l,m,n,t,23,h[47]),n=e(n,p,l,m,g,6,h[48]),m=e(m,n,p,l,z,10,h[49]),l=e(l,m,n,p,ba,15,h[50]),p=e(p,l,m,n,G,21,h[51]),n=e(n,
p,l,m,C,6,h[52]),m=e(m,n,p,l,x,10,h[53]),l=e(l,m,n,p,O,15,h[54]),p=e(p,l,m,n,k,21,h[55]),n=e(n,p,l,m,K,6,h[56]),m=e(m,n,p,l,ca,10,h[57]),l=e(l,m,n,p,I,15,h[58]),p=e(p,l,m,n,X,21,h[59]),n=e(n,p,l,m,r,6,h[60]),m=e(m,n,p,l,T,10,h[61]),l=e(l,m,n,p,t,15,h[62]),p=e(p,l,m,n,M,21,h[63]);q[0]=q[0]+n|0;q[1]=q[1]+p|0;q[2]=q[2]+l|0;q[3]=q[3]+m|0},sa:function(){var b=this.aa,c=b.G,d=8*this.Ja,e=8*b.D;c[e>>>5]|=128<<24-e%32;var f=a.floor(d/4294967296);c[(e+64>>>9<<4)+15]=(f<<8|f>>>24)&16711935|(f<<24|f>>>8)&4278255360;
c[(e+64>>>9<<4)+14]=(d<<8|d>>>24)&16711935|(d<<24|d>>>8)&4278255360;b.D=4*(c.length+1);this.ba();b=this.ta;c=b.G;for(d=0;4>d;d++)e=c[d],c[d]=(e<<8|e>>>24)&16711935|(e<<24|e>>>8)&4278255360;return b},W:function(){var a=g.W.call(this);a.ta=this.ta.W();return a}});y.fb=g.Ha(f);y.Jc=g.cc(f)})(Math);
(function(){var a=y.fa,b=a.ab,c=a.qa,a=y.ua,d=a.cb=b.extend({F:b.extend({ea:4,sc:a.fb,uc:1}),I:function(a){this.F=this.F.extend(a)},tb:function(a,b){for(var d=this.F,g=d.sc.create(),h=c.create(),r=h.G,s=d.ea,d=d.uc;r.length<s;){u&&g.update(u);var u=g.update(a).Z(b);g.reset();for(var q=1;q<d;q++)u=g.Z(u),g.reset();h.concat(u)}h.D=4*s;return h}});y.cb=function(a,b,c){return d.create(c).tb(a,b)}})();
y.fa.Xb||function(a){function b(b,c,d){var e=this.jb;e?this.jb=a:e=this.nb;for(var f=0;f<d;f++)b[c+f]^=e[f]}var c=y,d=c.fa,e=d.ab,f=d.qa,k=d.Wb,g=c.ja.bb,h=c.ua.cb,r=d.Xb=k.extend({F:e.extend(),Pa:function(a,b){return this.create(this.Ga,a,b)},Oa:function(a,b){return this.create(this.bc,a,b)},I:function(a,b,c){this.F=this.F.extend(c);this.ob=a;this.ec=b;this.reset()},reset:function(){k.reset.call(this);this.Ia()},Zc:function(a){this.ra(a);return this.ba()},Z:function(a){a&&this.ra(a);return this.sa()},
ea:4,Eb:4,Ga:1,bc:2,Ha:function(a){return{ya:function(b,c,d){return("string"==typeof c?A:w).ya(a,b,c,d)},ia:function(b,c,d){return("string"==typeof c?A:w).ia(a,b,c,d)}}}});d.Nc=r.extend({sa:function(){return this.ba(!0)},V:1});var s=c.mode={},u=(d.Ec=e.extend({Pa:function(a,b){return this.Zb.create(a,b)},Oa:function(a,b){return this.Yb.create(a,b)},I:function(a,b){this.gb=a;this.jb=b}})).extend();u.Zb=u.extend({Rb:function(a,c){var d=this.gb,e=d.V;b.call(this,a,c,e);d.oc(a,c);this.nb=a.slice(c,c+
e)}});u.Yb=u.extend({Rb:function(a,c){var d=this.gb,e=d.V,f=a.slice(c,c+e);d.mc(a,c);b.call(this,a,c,e);this.nb=f}});s=s.Fc=u;u=(c.Pb={}).Lc={Pb:function(a,b){for(var c=4*b,c=c-a.D%c,d=c<<24|c<<16|c<<8|c,e=[],h=0;h<c;h+=4)e.push(d);c=f.create(e,c);a.concat(c)},Cc:function(a){a.D-=a.G[a.D-1>>>2]&255}};d.Vb=r.extend({F:r.F.extend({mode:s,padding:u}),reset:function(){r.reset.call(this);var a=this.F,b=a.$,a=a.mode;if(this.ob==this.Ga)var c=a.Pa;else c=a.Oa,this.lb=1;this.gc=c.call(a,this,b&&b.G)},ib:function(a,
b){this.gc.Rb(a,b)},sa:function(){var a=this.F.padding;if(this.ob==this.Ga){a.Pb(this.aa,this.V);var b=this.ba(!0)}else b=this.ba(!0),a.Cc(b);return b},V:4});var q=d.Gc=e.extend({I:function(a){this.Ta(a)},toString:function(a){return(a||this.qc).stringify(this)}}),s=(c.za={}).ac={stringify:function(a){var b=a.Ma;a=a.Xa;return(a?f.create([1398893684,1701076831]).concat(a).concat(b):b).toString(g)},parse:function(a){a=g.parse(a);var b=a.G;if(1398893684==b[0]&&1701076831==b[1]){var c=f.create(b.slice(2,
4));b.splice(0,4);a.D-=16}return q.create({Ma:a,Xa:c})}},w=d.Mc=e.extend({F:e.extend({za:s}),ya:function(a,b,c,d){d=this.F.extend(d);var e=a.Pa(c,d);b=e.Z(b);e=e.F;return q.create({Ma:b,key:c,$:e.$,Pc:a,mode:e.mode,padding:e.padding,V:a.V,qc:d.za})},ia:function(a,b,c,d){d=this.F.extend(d);b=this.mb(b,d.za);return a.Oa(c,d).Z(b.Ma)},mb:function(a,b){return"string"==typeof a?b.parse(a,this):a}}),c=(c.Sa={}).ac={execute:function(a,b,c,d){d||(d=f.random(8));a=h.create({ea:b+c}).tb(a,d);c=f.create(a.G.slice(b),
4*c);a.D=4*b;return q.create({key:a,$:c,Xa:d})}},A=d.Kc=w.extend({F:w.F.extend({Sa:c}),ya:function(a,b,c,d){d=this.F.extend(d);c=d.Sa.execute(c,a.ea,a.Eb);d.$=c.$;a=w.ya.call(this,a,b,c.key,d);a.Ta(c);return a},ia:function(a,b,c,d){d=this.F.extend(d);b=this.mb(b,d.za);c=d.Sa.execute(c,a.ea,a.Eb,b.Xa);d.$=c.$;return w.ia.call(this,a,b,c.key,d)}})}();
(function(){for(var a=y.fa.Vb,b=y.ua,c=[],d=[],e=[],f=[],k=[],g=[],h=[],r=[],s=[],u=[],q=[],w=0;256>w;w++)q[w]=128>w?w<<1:w<<1^283;for(var A=0,t=0,w=0;256>w;w++){var x=t^t<<1^t<<2^t<<3^t<<4,x=x>>>8^x&255^99;c[A]=x;d[x]=A;var D=q[A],G=q[D],I=q[G],z=257*q[x]^16843008*x;e[A]=z<<24|z>>>8;f[A]=z<<16|z>>>16;k[A]=z<<8|z>>>24;g[A]=z;z=16843009*I^65537*G^257*D^16843008*A;h[x]=z<<24|z>>>8;r[x]=z<<16|z>>>16;s[x]=z<<8|z>>>24;u[x]=z;A?(A=D^q[q[q[I^D]]],t^=q[q[t]]):A=t=1}var K=[0,1,2,4,8,16,32,64,128,27,54],b=
b.$a=a.extend({Ia:function(){for(var a=this.ec,b=a.G,d=a.D/4,a=4*((this.hc=d+6)+1),e=this.fc=[],f=0;f<a;f++)if(f<d)e[f]=b[f];else{var g=e[f-1];f%d?6<d&&4==f%d&&(g=c[g>>>24]<<24|c[g>>>16&255]<<16|c[g>>>8&255]<<8|c[g&255]):(g=g<<8|g>>>24,g=c[g>>>24]<<24|c[g>>>16&255]<<16|c[g>>>8&255]<<8|c[g&255],g^=K[f/d|0]<<24);e[f]=e[f-d]^g}b=this.dc=[];for(d=0;d<a;d++)f=a-d,g=d%4?e[f]:e[f-4],b[d]=4>d||4>=f?g:h[c[g>>>24]]^r[c[g>>>16&255]]^s[c[g>>>8&255]]^u[c[g&255]]},oc:function(a,b){this.hb(a,b,this.fc,e,f,k,g,c)},
mc:function(a,b){var c=a[b+1];a[b+1]=a[b+3];a[b+3]=c;this.hb(a,b,this.dc,h,r,s,u,d);c=a[b+1];a[b+1]=a[b+3];a[b+3]=c},hb:function(a,b,c,d,e,f,h,g){for(var k=this.hc,l=a[b]^c[0],m=a[b+1]^c[1],r=a[b+2]^c[2],q=a[b+3]^c[3],s=4,t=1;t<k;t++)var u=d[l>>>24]^e[m>>>16&255]^f[r>>>8&255]^h[q&255]^c[s++],w=d[m>>>24]^e[r>>>16&255]^f[q>>>8&255]^h[l&255]^c[s++],x=d[r>>>24]^e[q>>>16&255]^f[l>>>8&255]^h[m&255]^c[s++],q=d[q>>>24]^e[l>>>16&255]^f[m>>>8&255]^h[r&255]^c[s++],l=u,m=w,r=x;u=(g[l>>>24]<<24|g[m>>>16&255]<<
16|g[r>>>8&255]<<8|g[q&255])^c[s++];w=(g[m>>>24]<<24|g[r>>>16&255]<<16|g[q>>>8&255]<<8|g[l&255])^c[s++];x=(g[r>>>24]<<24|g[q>>>16&255]<<16|g[l>>>8&255]<<8|g[m&255])^c[s++];q=(g[q>>>24]<<24|g[l>>>16&255]<<16|g[m>>>8&255]<<8|g[r&255])^c[s++];a[b]=u;a[b+1]=w;a[b+2]=x;a[b+3]=q},ea:8});y.$a=a.Ha(b)})();
// Input 2
function ea(a,b){var c=[];a.font=b;c[0]=a.measureText("WWWWI").width;a.font="bold "+b;c[1]=a.measureText("WWWWI").width;a.font="lighter "+b;c[2]=a.measureText("WWWWI").width;return c}
function fa(a){if(a.fontsize){var b=a.canvas.getContext("2d"),c="300px "+a.fontFamily+", sans",d="300px "+a.fontFamily+", serif",e=ea(b,"300px sans"),f=ea(b,"300px serif"),c=ea(b,c),d=ea(b,d),k=c[1]!=d[1]||c[1]==e[1]||d[1]==f[1],g=c[2]!=d[2]||c[2]==e[2]||d[2]==f[2];c[0]!=d[0]||c[0]==e[0]||d[0]==f[0]||k||g?setTimeout(function(){fa(a)},20):(a.Hb="normal "+a.fontsize+"px "+a.fontFamily,a.ca="bold "+a.fontsize+"px "+a.fontFamily,a.Fb="lighter "+a.fontsize+"px "+a.fontFamily,b.font=a.Hb,e=b.measureText("W").width,
b.font=a.ca,f=b.measureText("W").width,b.font=a.Fb,b=b.measureText("W").width,c=Math.max(e,f,b),a.zc=parseInt((c-e)/2,10),a.ic=parseInt((c-f)/2,10),a.vc=parseInt((c-b)/2,10),a.font={},a.font.N=a.fontsize,a.font.L=c,a.debug("Using font-family '"+a.fontFamily+"' ["+c+" x "+a.fontsize+"]"),ga(a))}else new ha(a.zb,function(b){a.font=b;ga(a)},a.options.debug),a.ca&&new ha(a.ca,function(b){a.P=b;ga(a)},a.options.debug)}
function ia(a,b){var c=this;if(!(a instanceof HTMLCanvasElement))throw Error("First argument to TTVCanvas constructor must be an HTMLCanvasElement (was "+a+")");c.U=B("#000000 #b21818 #18b218 #b26818 #1818b2 #b218b2 #18b2b2 #b2b2b2".split(" "));c.T=B("#686868 #ff5454 #54ff54 #ffff54 #5454ff #ff54ff #54ffff #ffffff".split(" "));c.zb="qemu-vgafont";c.fontFamily="monospace";c.la=[];c.canvas=a;c.debug=function(a){b.debug?b.debug("canvasview.js: "+a):alert("canvasview.js: "+a)};c.options=b;b.fontsize&&
(c.fontsize=b.fontsize);b.Y&&(c.Y=b.Y);b.font&&(c.zb=b.font);b.Ab&&(c.fontFamily=b.Ab);b.P&&(c.ca=b.P);b.Y&&(c.Y=b.Y);b.Q&&(c.Q=b.Q);b.la&&c.la.push(b.la);c.cursor={};c.cursor.x=0;c.cursor.y=0;c.cursor.visible=!0;c.o=new E({debug:c.options.debug,A:c.options.A,width:c.options.width,height:c.options.height,jc:function(a,b,d){ja(c,a,b,d)},cursor:function(a,b,d){a>=c.o.width&&(a=c.o.width-1);ja(c,b,a,a);ja(c,c.cursor.y,c.cursor.x,c.cursor.x);c.cursor.x=a;c.cursor.y=b;c.cursor.visible=d},Bc:function(a){if(c.Q&&
((a.title||a.icon)&&c.Q(a),a.border)){var b=a.border[0];0<=b&&8>b?c.Q({border:c.U[b],width:a.border[1]*c.font.L}):10<=b&&18>b?c.Q({border:c.T[b%10],width:a.border[1]*c.font.L}):c.Q({border:null})}}});c.na=new ka(c.o,c.options.debug);c.xa=[];for(var d=0;d<c.o.height;d++)c.xa[d]={min:0,max:c.o.width-1};setTimeout(function(){fa(c)},1);return this}
function ga(a){if(!a.fontsize){if(!a.font)return;if(a.ca){if(!a.P)return;if(a.font.L!=a.P.L||a.font.N!=a.P.N)a.debug("Normal font size ["+a.font.L+"x"+a.font.N+"] and bold font size ["+a.P.L+"x"+a.font.N+"] mismatch"),a.P=void 0}}a.Y&&(a.canvas.setAttribute("width",a.o.width*a.font.L),a.canvas.setAttribute("height",a.o.height*a.font.N));la(a);a.la.forEach(function(a){a()})}function ma(a){return{nc:a.o.freeze(),na:a.na.buffer}}ia.prototype.Ea=function(a){this.o.Ea(a.nc);this.na.buffer=a.na};
function ja(a,b,c,d){if(b>=a.o.height||0>c||d>=a.o.width)throw Error("makeSpanDirty "+b+" "+a.o.height+" "+c+" "+d+" "+a.o.width);a=a.xa[b];a.min>c&&(a.min=c);a.max<d&&(a.max=d)}
function la(a){var b=a.canvas.getContext("2d");b.textBaseline="bottom";b.lineWidth=1;b.beginPath();var c=a.font.L,d=a.font.N,e,f,k;if(a.fontsize)for(g=0;g<a.o.height;g++){h=a.xa[g];for(r=h.min;r<=h.max;r++)s=g*a.o.width+r,(t=a.cursor.x==r&&a.cursor.y==g&&a.cursor.visible)?(u=a.o.p.r.C[s]%10,t=(9<u||a.o.p.r.bold[s]?a.T:a.U)[u]):(q=a.o.p.r.B[s]%10,t=(9<q?a.T:a.U)[q]),f!=t&&(b.fillStyle=f=t),b.fillRect(r*c,g*d,c,d);for(r=h.min;r<=h.max;r++)s=g*a.o.width+r,w=a.o.p.r.bold[s],A=a.o.p.r.text[s],(t=a.cursor.x==
r&&a.cursor.y==g&&a.cursor.visible)?(q=a.o.p.r.B[s]%10,u=(9<q?a.T:a.U)[q]):(u=a.o.p.r.C[s]%10,u=(9<u||w?a.T:a.U)[u]),32!=A.charCodeAt(0)&&(f!=u&&(b.fillStyle=f=u),q=a.Hb,t=a.zc,w&&(q=a.ca,t=a.ic),a.o.p.r.K[s]&&(q=a.Fb,t=a.vc),e!=q&&(b.font=e=q),b.fillText(A,r*c+t,(g+1)*d),b.stroke()),a.o.p.r.M[s]&&(u!=k&&(b.stroke(),b.strokeStyle=k=u,b.beginPath()),b.moveTo(r*c,(g+1)*d-1),b.lineTo((r+1)*c,(g+1)*d-1));h.min=a.o.width-1;h.max=0}else for(var g=0;g<a.o.height;g++){for(var h=a.xa[g],r=h.min;r<=h.max;r++){var s=
g*a.o.width+r,u=a.o.p.r.C[s]%10,q=a.o.p.r.B[s]%10,w=a.o.p.r.bold[s],A=a.o.p.r.text[s],t=a.cursor.x==r&&a.cursor.y==g&&a.cursor.visible;t?(t=(9<u||w?a.T:a.U)[u],u=(9<q?a.T:a.U)[q]):(u=(9<u||w?a.T:a.U)[u],t=(9<q?a.T:a.U)[q]);w&&a.P?a.P.yb(b,A,r*c,g*d,u,t):a.font.yb(b,A,r*c,g*d,u,t);a.o.p.r.M[s]&&(u!=k&&(b.stroke(),b.strokeStyle=k=u,b.beginPath()),b.moveTo(r*c,(g+1)*d-1),b.lineTo((r+1)*c,(g+1)*d-1))}h.min=a.o.width-1;h.max=0}b.stroke()};
// Input 3
function B(a){if("object"!=typeof a||null===a)return a;var b="undefined"!=typeof a.length?Array(a.length):{},c;for(c in a)b[c]="object"==typeof a[c]?B(a[c]):a[c];return b};
// Input 4
function na(a){for(var b=[],c=0;c<a.length;){var d=oa(a,c),e=oa(a,c+4),f=oa(a,c+8);if(0>f)throw Error("The stream seems to be broken [chunk size < 0]");if(0==f&&c+12+f>a.length)break;if(c+12+f>a.length)throw Error("The stream seems to be broken ["+f+";"+(c+12+f)+">"+a.length+"]");for(var k=a.substr(c+12,f),c=c+(f+12),g="",h=0;h<k.length;h++)g+=String.fromCharCode(k.charCodeAt(h)&255);b.push({time:d+e/1E6,Wc:f,data:g})}return b}
function oa(a,b){return(a.charCodeAt(b+3)&255)<<24|(a.charCodeAt(b+2)&255)<<16|(a.charCodeAt(b+1)&255)<<8|a.charCodeAt(b)&255};
// Input 5
function da(a){function b(a){return("0"+a).slice(-2)}var c;if(a.title||""===a.title)c=a.title;else{c=a.name.split("/").reverse()[0];var d=c.substr(-4,4);if(".rec"==d||".tty"==d)c=c.substr(0,c.length-4)}var e=document.createElement("div");e.setAttribute("class","tty");e.setAttribute("style","display:none;");d=document.createElement("table");d.setAttribute("class","tty");d.id="table";var f=document.createElement("tr"),k=document.createElement("td"),g=document.createElement("td"),h=document.createElement("td"),
r=document.createElement("img"),s=document.createElement("img"),u=document.createTextNode(c);f.setAttribute("class","tty");f.id="row1";k.setAttribute("class","tty");g.setAttribute("class","tty");h.setAttribute("class","tty");k.id="cell11";g.id="cell12";h.id="cell13";r.setAttribute("class","tty");r.id="img11";s.setAttribute("class","tty");s.id="img13";a.onclose&&(s.onclick=a.onclose);k.appendChild(r);g.appendChild(u);h.appendChild(s);f.appendChild(k);f.appendChild(g);f.appendChild(h);d.appendChild(f);
f=document.createElement("tr");f.setAttribute("class","tty");f.id="row2";var q=document.createElement("td");q.setAttribute("class","tty");q.id="cell21";var w=document.createElement("canvas");w.setAttribute("class","tty");w.id="canvas";q.setAttribute("colspan","3");w.width=1;w.height=1;q.appendChild(w);f.appendChild(q);d.appendChild(f);g=document.createElement("tr");g.setAttribute("class","tty");g.id="row3";h=document.createElement("td");r=document.createElement("td");s=document.createElement("td");
h.setAttribute("class","tty");r.setAttribute("class","tty");s.setAttribute("class","tty");h.id="cell31";r.id="cell32";s.id="cell33";var A=document.createTextNode("TermTV"),f=document.createElement("span"),t=document.createElement("span"),x=document.createElement("span"),k=document.createElement("span"),D=document.createElement("span"),G=document.createElement("span"),I=document.createElement("span"),z=document.createElement("span"),K=document.createElement("span"),M=document.createElement("progress"),
O=document.createTextNode("00:00:00"),T=document.createTextNode("00:00:00");x.setAttribute("style","display:none;");G.setAttribute("style","display:none;");f.setAttribute("class","tty");t.setAttribute("class","tty");x.setAttribute("class","tty");k.setAttribute("class","tty");D.setAttribute("class","tty");G.setAttribute("class","tty");I.setAttribute("class","tty");f.id="input321";t.id="input322a";x.id="input322b";k.id="input326";D.id="input327a";G.id="input327b";I.id="input33";I.onclick=function(){var a=
w.toDataURL("image/png"),a=a.replace("image/png","image/octet-stream");document.location.href=a;return!1};z.setAttribute("class","tty");K.setAttribute("class","tty");z.id="span323";K.id="span325";M.max=1;M.value=0;z.appendChild(O);K.appendChild(T);h.appendChild(A);r.appendChild(f);r.appendChild(t);r.appendChild(x);r.appendChild(z);r.appendChild(M);r.appendChild(K);r.appendChild(k);r.appendChild(D);r.appendChild(G);s.appendChild(I);g.appendChild(h);g.appendChild(r);g.appendChild(s);a.controls&&d.appendChild(g);
var g=document.createElement("tr"),h=document.createElement("td"),C=document.createElement("div");h.setAttribute("style","max-width:1px;");h.setAttribute("colspan","3");C.setAttribute("class","tty");C.id="div4";C.onscroll=function(){C.Dc=C.scrollHeight-C.scrollTop!=C.clientHeight};h.appendChild(C);g.appendChild(h);a.debug&&d.appendChild(g);e.appendChild(d);if(a.debug){var X=parseInt(a.debug,10);a.debugLevel=a.debug;a.debug=function(a){if(a&&(1!=X||"emu"!=a.substr(9,3))){if("par"==a.substr(9,3)){var b=
document.createElement("div");b.setAttribute("style","color:green");b.appendChild(document.createTextNode(a));C.appendChild(b)}else C.appendChild(document.createTextNode(a)),C.appendChild(document.createElement("br"));C.Dc||(C.scrollTop=C.scrollHeight)}}}else a.debug=function(){};a.onready=function(a){T.nodeValue=b(a.getUTCHours())+":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds());e.style.display="inherit"};a.callback=function(a){if(a.title){var b=c;b.length&&(b+=": ");a.title&&(b+=a.title);u.nodeValue=
b}a.border&&(b=(a.width||0)+"px ",q.Jb=q.getAttribute("style"),q.setAttribute("style","padding:"+b+b+b+b+"; background-color:"+a.border+";"));null==a.border&&q.Jb&&q.setAttribute("style",q.Jb)};a.onupdate=function(a,c){O.nodeValue=b(a.getUTCHours())+":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds());M.value=c};a.oncompletion=function(){x.setAttribute("style","display:none;");t.setAttribute("style","display:inline;");O.nodeValue="--:--:--"};a.onbookmark=function(){D.setAttribute("style","display:none;");
G.setAttribute("style","display:inline;")};a.onpause=function(){x.setAttribute("style","display:none;");t.setAttribute("style","display:inline;")};a.onplay=function(){t.setAttribute("style","display:none;");x.setAttribute("style","display:inline;")};e.ga=new F(w,a);f.onclick=function(){e.ga.Wa()};t.onclick=function(){e.ga.Ua()};x.onclick=function(){e.ga.Ua()};k.onclick=function(){e.ga.Sb()};D.onclick=function(){e.ga.Ra()};G.onclick=function(){e.ga.Ra()};return e}window.TTVDisplay=da;
// Input 6
function E(a){this.rb=a.jc;this.Tb=a.Bc;this.vb=a.cursor;this.A=a.A;this.debug=function(b){a.debug?a.debug("emulate.js: "+b):alert("emulate.js: "+b)};this.width=a.width||80;this.height=a.height||24;pa(this);return this}
function pa(a){a.p={};a.cursor={};a.cursor.x=0;a.cursor.y=0;a.cursor.bold=!1;a.cursor.M=!1;a.cursor.K=!1;a.cursor.blink=!1;a.cursor.ha=!1;a.cursor.Db=!1;a.cursor.C=7;a.cursor.B=0;a.cursor.visible=!0;a.p.r={};a.p.r.text=[];a.p.r.bold=[];a.p.r.M=[];a.p.r.K=[];a.p.r.blink=[];a.p.r.C=[];a.p.r.B=[];a.p.Ba=!1;a.p.wb=B(a.cursor);a.p.da={};a.p.da.x=0;a.p.da.y=0;a.p.pb=!0;for(var b=0;b<a.width*a.height;b++)a.p.r.text.push(" "),a.p.r.bold.push(!1),a.p.r.M.push(!1),a.p.r.K.push(!1),a.p.r.blink.push(!1),a.p.r.C.push(7),
a.p.r.B.push(0);a.Ca=B(a.p);a.mode={};a.mode.lc=!0;a.mode.scroll="jump";a.mode.Ba=!1;a.mode.ma="screen";a.mode.Qc=!0;a.mode.wc=!1;a.mode.xc=!1;a.mode.ub=1;a.mode.Uc=!1;a.mode.Cb=!1;a.mode.Tc=0;a.mode.Yc=!0;a.mode.yc="cr";a.s={};a.s.top=0;a.s.bottom=a.height-1;a.Da={};for(b=0;b<a.width;b++)a.Da[b]=0==b%8;a.pa="";a.ka="";a.H={};a.H.Rc="us";a.H.Sc="line";a.H.S="g0"}E.prototype.freeze=function(){return B(this)};
E.prototype.Ea=function(a){this.p=B(a.p);this.Ca=B(a.Ca);this.mode=B(a.mode);this.cursor=B(a.cursor);this.s=B(a.s);this.Da=B(a.Da);this.H=B(a.H);this.pa=a.pa;this.ka=a.ka;for(var b=0;b<this.height;b++)H(this,b,0,this.height-1);J(this,{title:a.pa,icon:a.ka});L(this)};function N(a){return String.fromCharCode(parseInt(a,16))}
E.prototype.Ka={ad:{},$c:{"#":N("A3")},Xc:{_:" ","`":N("2666"),a:N("2591"),b:N("2409"),c:N("240C"),d:N("240D"),e:N("240A"),f:N("B0"),g:N("B1"),h:N("2424"),i:N("240B"),j:N("2518"),k:N("2510"),l:N("250C"),m:N("2514"),n:N("253C"),q:N("2500"),t:N("2524"),u:N("251C"),v:N("2534"),w:N("252C"),x:N("2502"),y:N("2264"),z:N("2265"),"{":N("3C0"),"|":N("2260"),"}":N("A3"),"~":N("B7")}};function H(a,b,c,d){a.rb&&a.rb(b,c,d)}function J(a,b){a.Tb&&a.Tb(b)}
function L(a){a.vb&&a.vb(a.cursor.x,a.cursor.y,a.cursor.visible)}function qa(a,b,c,d){!d&&2<a.A&&a.debug("SET_MARGIN="+b+" "+c);b-=1;c-=1;b+1>=c&&(b=c-1);0>b&&(b=0);b>a.height-2&&(b=a.height-2);1>c&&(c=1);c>a.height-1&&(c=a.height-1);b+1>=c&&a.debug("numbers do not obey the laws of arithmetic in setMargins");a.s.top=b;a.s.bottom=c;P(a,1,1)}
function Q(a,b,c){2<a.A&&a.debug("CURSOR_STACK="+b+" [+attrib="+c+"]");"push"==b&&(c?a.p.wb=B(a.cursor):(a.p.da.x=a.cursor.x,a.p.da.y=a.cursor.y));"pop"==b&&(c?a.cursor=B(a.p.wb):(a.cursor.x=a.p.da.x,a.cursor.y=a.p.da.y));L(a)}
function ra(a,b,c){!c&&2<a.A&&a.debug("SET_ATTRIB="+(b[0]?b:"0"));var d,e;b[0]&&0!=b[0]?30<=b[0]&&37>=b[0]?d=b[0]-30:39==b[0]?d=7:40<=b[0]&&47>=b[0]?e=b[0]-40:49==b[0]?e=0:90<=b[0]&&97>=b[0]?d=b[0]-90+10:99==b[0]?d=7:100<=b[0]&&107>=b[0]?e=b[0]-100+10:109==b[0]?e=0:1==b[0]?(a.cursor.bold=!0,a.cursor.K=!1):2==b[0]?(a.cursor.K=!0,a.cursor.bold=!1):21!=b[0]&&(22==b[0]?(a.cursor.K=!1,a.cursor.bold=!1):7==b[0]||27==b[0]?(7!=b[0]||a.cursor.ha||(a.cursor.ha=!0,d=a.cursor.C,e=a.cursor.B),27==b[0]&&a.cursor.ha&&
(a.cursor.ha=!1,e=a.cursor.C,d=a.cursor.B)):4==b[0]||24==b[0]?a.cursor.M=4==b[0]:5==b[0]||25==b[0]?a.cursor.blink=5==b[0]:8==b[0]||28==b[0]?a.cursor.Db=8==b:10==b[0]?a.H.S=void 0:11==b[0]?a.H.S=void 0:38==b[0]&&5==b[1]?(8>b[2]?d=b[2]:16>b[2]&&(d=b[2]-2),a.debug("Warning: 256-foreground color ("+b[2]+") not supported."),b=b.slice(2)):48==b[0]&&5==b[1]?(8>b[2]?e=b[2]:16>b[2]&&(e=b[2]-2),a.debug("Warning: 256-background color ("+b[2]+") not supported."),b=b.slice(2)):38==b[0]&&2==b[1]?(a.debug("Warning: 24bit color ("+
b.slice(2)+") not supported."),b=b.slice(4)):48==b[0]&&2==b[1]?(a.debug("Warning: 24bit color ("+b.slice(2)+") not supported."),b=b.slice(4)):a.debug("Warning: ignoring setAttribute("+b+")")):(a.cursor.bold=!1,a.cursor.M=!1,a.cursor.K=!1,a.cursor.blink=!1,a.cursor.ha=!1,a.cursor.Db=!1,d=7,e=0);a.cursor.ha^a.p.Ba&&(c=d,d=e,e=c);void 0!=d&&(a.cursor.C=d);void 0!=e&&(a.cursor.B=e);1<b.length&&ra(a,b.slice(1),!0)}
function R(a,b){2<a.A&&a.debug("STRING=["+a.cursor.x+"/"+a.cursor.y+";"+a.cursor.C+";"+a.cursor.B+";"+b+"]["+b.length+"]");for(var c=0;c<b.length;c++){var d=a,e=b[c];2<d.A&&d.debug("CHAR=["+d.cursor.x+"/"+d.cursor.y+";"+d.cursor.C+";"+d.cursor.B+";"+e+"]");d.H.S&&d.H[d.H.S]&&d.Ka[d.H[d.H.S]]&&d.Ka[d.H[d.H.S]][e]&&(e=d.Ka[d.H[d.H.S]][e]);if(d.cursor.x==d.width)if(d.p.pb){var f="screen"==d.mode.ma?d.height:d.s.bottom+1;d.cursor.x=0;d.cursor.y++;d.cursor.y>=f&&(d.cursor.y==f&&d.scroll(1),d.cursor.y=
f-1)}else d.cursor.x--;d.mode.Cb?(sa(d,d.width-1,d.cursor.y),ta(d,e,d.cursor.x,d.cursor.y),H(d,d.cursor.y,d.cursor.x,d.width-1)):(ua(d,e,d.cursor.x,d.cursor.y),H(d,d.cursor.y,d.cursor.x,d.cursor.x));d.cursor.x++;L(d)}}
function S(a,b){2<a.A&&a.debug("SPECIAL_CHAR="+b);switch(b){case "carriageReturn":a.cursor.x=0;L(a);break;case "backspace":0<a.cursor.x&&(a.cursor.x--,L(a));break;case "lineFeed":case "formFeed":case "verticalTab":a.cursor.y++;a.cursor.y==a.s.bottom+1&&(a.scroll(1),a.cursor.y=a.s.bottom);a.cursor.y>=a.height&&(a.cursor.y=a.height-1);"crlf"==a.mode.yc&&(a.cursor.x=0);L(a);break;case "horizontalTab":do a.cursor.x++;while(a.cursor.x<a.width&&!a.Da[a.cursor.x]);L(a);break;case "bell":J(a,{bell:"bell"});
break;default:a.debug("Warning: skipping specialChar event for key "+b)}}
function U(a,b,c){2<a.A&&a.debug("ARROW=["+a.cursor.x+"/"+a.cursor.y+"] + "+b+" "+c);var d="screen"==a.mode.ma?0:a.s.top,e="screen"==a.mode.ma?a.height:a.s.bottom+1;switch(b){case "up":a.cursor.y-=c;a.cursor.y<d&&(a.cursor.y=d);break;case "down":a.cursor.y+=c;a.cursor.y>=e&&(a.cursor.y=e-1);break;case "left":a.cursor.x-=c;0>a.cursor.x&&(a.cursor.x=0);break;case "right":a.cursor.x+=c;a.cursor.x>=a.width&&(a.cursor.x=a.width-1);break;default:a.debug("Can't handle arrow event with direction "+b);return}L(a)}
function va(a,b){2<a.A&&a.debug("DELETE_CHARS="+b);for(var c=0;c<b;c++){var d=a,e=a.width-1+a.cursor.y*d.width;d.p.r.text.splice(e,0," ");d.p.r.bold.splice(e,0,!1);d.p.r.M.splice(e,0,!1);d.p.r.K.splice(e,0,!1);d.p.r.blink.splice(e,0,!1);d.p.r.C.splice(e,0,7);d.p.r.B.splice(e,0,0);sa(a,a.cursor.x,a.cursor.y)}H(a,a.cursor.y,a.cursor.x,a.width-1)}
function V(a,b,c){2<a.A&&a.debug("INDEX="+b);switch(b){case "down":for(b=0;b<c;b++)a.cursor.y==a.s.bottom?a.scroll(1):a.cursor.y++;L(a);break;case "up":for(b=0;b<c;b++)a.cursor.y==a.s.top?a.scroll(-1):a.cursor.y--;L(a);break;case "nextLine":V(a,"down",c);a.cursor.x=0;L(a);break;case "prevLine":V(a,"up",c);a.cursor.x=0;L(a);break;default:a.debug("Can't index with method "+b)}}
function W(a,b,c){2<a.A&&a.debug("MODE="+b+" ["+c+"]");switch(b){case "insert":a.mode.Cb=c;break;case "cursorKeyANSI":a.mode.lc=c;break;case "keypad":a.mode.Vc=c;break;case "mouseTrackingUp":a.mode.xc=c;break;case "mouseTrackingDown":a.mode.wc=c;break;case "scroll":a.mode.scroll=c;break;case "autoWrap":a.p.pb=c;break;case "cursor":a.cursor.visible=c;L(a);break;case "cursorBlink":a.cursor.blink=c;break;case "width":a.debug("width="+c);break;case "height":a.debug("height="+c);break;case "currentScreen":if(c!=
a.mode.ub)for(a.debug("Exchange screens"),b=a.p,a.p=a.Ca,a.Ca=b,a.mode.ub=c,c=0;c<a.height;c++)H(a,c,0,a.width-1);break;case "originMode":a.mode.ma=c;P(a,1,1);break;case "reverseScreen":if(c!=a.p.Ba)for(a.debug("Reverse screen"),a.p.Ba=c,c=a.p.r.C,a.p.r.C=a.p.r.B,a.p.r.B=c,c=a.cursor.C,a.cursor.C=a.cursor.B,a.cursor.B=c,c=0;c<a.height;c++)H(a,c,0,a.width-1);break;case "borderColor":J(a,{border:c});a.debug("Setting border to [col="+c[0]+"; width="+c[1]+"]");break;default:a.debug("Warning: can't handle mode change '"+
b+"' to '"+c+"'")}}function Y(a,b){2<a.A&&a.debug("ERASE_IN_LINE="+b);var c,d;switch(b){case "toEnd":c=a.cursor.x;d=a.width;break;case "toStart":c=0;d=a.cursor.x+1;break;case "whole":c=0;d=a.width;break;default:a.debug("Can't eraseInLine with method '"+b+"'");return}for(var e=c;e<d;e++)ua(a," ",e,a.cursor.y);H(a,a.cursor.y,c,d-1)}
function wa(a,b){2<a.A&&a.debug("ERASE_IN_DISPLAY="+b);var c,d;switch(b){case "toEnd":Y(a,"toEnd");c=a.cursor.y+1;d=a.height;break;case "toStart":Y(a,"toStart");c=0;d=a.cursor.y;break;case "whole":c=0;d=a.height;break;default:a.debug("Can't eraseInDisplay with method '"+b+"'");return}for(var e=c;e<d;e++)for(var f=0;f<a.width;f++)ua(a," ",f,e);for(e=c;e<d;e++)H(a,e,0,a.width-1)}
function P(a,b,c){2<a.A&&a.debug("GOTO="+b+","+c);b-=1;var d=c-1;0>b&&(b=0);b>a.width&&(b=a.width);0>d&&(d=0);"screen"==a.mode.ma?d>=a.height&&(d=a.height-1):(d+=a.s.top,d>a.s.bottom&&(d=a.s.bottom));a.cursor.x=b;0<=c&&(a.cursor.y=d);L(a)}function sa(a,b,c){b+=c*a.width;a.p.r.text.splice(b,1);a.p.r.bold.splice(b,1);a.p.r.M.splice(b,1);a.p.r.K.splice(b,1);a.p.r.blink.splice(b,1);a.p.r.C.splice(b,1);a.p.r.B.splice(b,1)}
function ta(a,b,c,d){c+=d*a.width;a.p.r.text.splice(c,0,b);a.p.r.bold.splice(c,0,a.cursor.bold);a.p.r.M.splice(c,0,a.cursor.M);a.p.r.K.splice(c,0,a.cursor.K);a.p.r.blink.splice(c,0,a.cursor.blink);a.p.r.C.splice(c,0,a.cursor.C);a.p.r.B.splice(c,0,a.cursor.B)}
function ua(a,b,c,d){c+=d*a.width;a.p.r.text.splice(c,1,b);a.p.r.bold.splice(c,1,a.cursor.bold);a.p.r.M.splice(c,1,a.cursor.M);a.p.r.K.splice(c,1,a.cursor.K);a.p.r.blink.splice(c,1,a.cursor.blink);a.p.r.C.splice(c,1,a.cursor.C);a.p.r.B.splice(c,1,a.cursor.B)}function xa(a,b,c){b+=c*a.width;a.p.r.text[b]=" ";a.p.r.bold[b]=!1;a.p.r.M[b]=!1;a.p.r.K[b]=!1;a.p.r.blink[b]=!1;a.p.r.C[b]=7;a.p.r.B[b]=0}
function ya(a,b,c){for(var d=0;d<a.width;d++){var e=a,f=d+b*a.width,k=d+c*a.width;e.p.r.text.splice(k,1,e.p.r.text[f]);e.p.r.bold.splice(k,1,e.p.r.bold[f]);e.p.r.M.splice(k,1,e.p.r.M[f]);e.p.r.K.splice(k,1,e.p.r.K[f]);e.p.r.blink.splice(k,1,e.p.r.blink[f]);e.p.r.C.splice(k,1,e.p.r.C[f]);e.p.r.B.splice(k,1,e.p.r.B[f])}}
E.prototype.scroll=function(a){2<this.A&&this.debug("SCROLL="+a);if(0!=a&&!isNaN(a)){if(0<a)for(var b=0;b<a;b++)for(var c=0;c<this.width;c++)ta(this," ",0,this.s.bottom+1),sa(this,0,this.s.top);else for(b=a;0<b;b--)for(c=0;c<this.width;c++)sa(this,0,this.s.bottom),ta(this," ",0,this.s.top);for(a=this.s.top;a<=this.s.bottom;a++)H(this,a,0,this.width-1)}};function Z(a,b,c){a.debug("Warning: Event '"+b+"' not implemented: "+c)}function za(a,b){Z(a,"lineAttr",b)};
// Input 7
var Aa={},$={},Ba="./fonts/";
function ha(a,b,c){var d=this;if(Aa[a])b(Aa[a],null);else if($[a])$[a].wa.push(b);else{d.debug=function(a){c("font.js: "+a)};var e=$[a]={R:new Image,wa:[b]};e.R.onload=function(){e.tc=!0;e.Gb&&g(a)};var f=Ba+a;e.R.onerror=function(){alert("ERROR[1] - Loading image '"+f+".png' failed.");e.wa.forEach(function(a){a(null,"Couldn't load stats file")});delete $[a]};e.R.src=f+".png";var k=new XMLHttpRequest;k.open("GET",f+".txt",!0);k.onload=function(){200!=k.status?(alert("ERROR[0] - HTTP request '"+f+
".txt': "+k.statusText+" ["+k.status+"]"),e.wa.forEach(function(a){a(null,"Couldn't load stats file")}),delete $[a]):(e.Gb=k.responseText,e.tc&&g(a))};k.send(null);var g=function(a){var b=$[a],c=new h(a,b.R,b.Gb);Aa[a]=c;delete $[a];d.debug(a+" ["+c.L+"x"+c.N+"] loaded.");b.wa.forEach(function(a){a(c,null)})},h=function(a,b,c){Aa[a]=this;this.R=b;var e=this.La={};this.Na={};var f=0,g=0,h=0,k=0,D=0;c.split("\n").forEach(function(a){if(a.length)if(/^\d+$/.exec(a))e[a]=[f++,g],D=parseInt(a,10),h++;else if(/^y$/.exec(a))f>
k&&(k=f),f=0,g++;else{var b=/^r(\d+)$/.exec(a);if(b){a=parseInt(b[1],10);for(b=D+1;b<=D+a;b++)e[b]=[f++,g];h+=a;D+=a}else d.debug('Stats file is corrupt, line="'+a+'"')}});f>k&&(k=f);this.kc=h;this.N=this.R.naturalHeight/(g+1);this.L=this.R.naturalWidth/k;this.L!=Math.floor(this.L)&&d.debug("font loading of "+a+" failed: image width is not a multiple of the character count (image width = "+this.R.naturalWidth+", character count = "+this.kc+")")};h.prototype.yb=function(a,b,c,e,f,g){var h=this.La[b.charCodeAt(0)];
if(void 0===h&&(h=this.La[0],void 0===h&&(h=this.La[63],void 0===h))){d.debug("Can't draw '"+b+"', it is not mapped and neither is the missing character");return}b=f.substr(1)+g.substr(1)+h[1];this.Na[b]||(this.Na[b]=this.rc(f,g,h[1]));a.drawImage(this.Na[b],h[0]*this.L,0,this.L,this.N,c,e,this.L,this.N)};h.prototype.rc=function(a,b,c){var d=this.R.naturalWidth,e=this.N,f=c*this.N;c=document.createElement("canvas");c.width=d;c.height=e;var g=c.getContext("2d");g.drawImage(this.R,0,f,d,e,0,0,d,e);
for(var f=g.getImageData(0,0,d,e),h=g.createImageData(d,e),d=d*e*4,e=0;e<d;e+=4){var k=127<f.data[e]?b:a;h.data[e]=parseInt(k.substring(1,3),16);h.data[e+1]=parseInt(k.substring(3,5),16);h.data[e+2]=parseInt(k.substring(5,7),16);h.data[e+3]=255}g.putImageData(h,0,0);return c}}};
// Input 8
function aa(a){function b(){c.style.opacity=parseFloat(c.style.opacity)+0.03;if(0.79<c.style.opacity){var d=new da(a);k.appendChild(d)}else setTimeout(b,1)}var c=document.createElement("span");c.setAttribute("style","position:fixed;top:0px;left:0px;width:100%;height:100%;opacity:0;background-color:black;");var d=document.getElementsByTagName("body")[0];d.appendChild(c);var e=document.createElement("table");e.setAttribute("style","position:fixed;top:0px;left:0px;width:100%;height:100%");var f=document.createElement("tr"),
k=document.createElement("td");k.align="center";a.onclose=function(){d.removeChild(e);d.removeChild(c)};d.appendChild(e);e.appendChild(f);f.appendChild(k);b()}window.TTVOverlay=aa;
// Input 9
function ka(a,b){this.debug=function(a){b?b("parse.js: "+a):alert("parse.js: "+a)};this.o=a;this.buffer="";return this}ka.prototype.parse=function(a){for(this.buffer+=a;Ca(this););};
function Ca(a){for(var b=0;b<a.Qa.length;b++){var c=a.Qa[b][0].exec(a.buffer);if(c&&0!=c[0].length)return a.Qa[b][1].call(a,c),a.buffer=a.buffer.substr(c[0].length),!0}50<a.buffer.length&&"\u001b"==a.buffer[0]&&(a.debug("Unknown escape sequence: "+a.buffer[1].charCodeAt(0).toString(16)+" "+a.buffer[2].charCodeAt(0).toString(16)+" "+a.buffer[3].charCodeAt(0).toString(16)+" "+a.buffer[4].charCodeAt(0).toString(16)+" "+a.buffer[5].charCodeAt(0).toString(16)+" "+a.buffer[6].charCodeAt(0).toString(16)+
" "+a.buffer[7].charCodeAt(0).toString(16)+" "+a.buffer[8].charCodeAt(0).toString(16)+" "+a.buffer[9].charCodeAt(0).toString(16)+" ["+a.buffer+"]"),R(a.o,"\x00"),a.buffer=a.buffer.substr(1));return!1}
ka.prototype.Qa=[[/^[\x20-\x7F]+/,function(a){R(this.o,a[0])}],[/^[\xC2-\xDF][\x80-\xBF]/,function(a){R(this.o,String.fromCharCode((a[0].charCodeAt(0)&31)<<6|a[0].charCodeAt(1)&63))}],[/^\x1b\[([0-9;]*)m/,function(a){ra(this.o,a[1].split(";"))}],[/^[\xE0-\xEF][\x80-\xBF][\x80-\xBF]/,function(a){R(this.o,String.fromCharCode((a[0].charCodeAt(0)&15)<<12|(a[0].charCodeAt(1)&63)<<6|a[0].charCodeAt(2)&63))}],[/^[\xF0-\xF4][\x80-\xBF][\x80-\xBF][\x80-\xBF]/,function(a){R(this.o,String.fromCharCode((a[0].charCodeAt(0)&
7)<<18|(a[0].charCodeAt(1)&63)<<12|(a[0].charCodeAt(2)&63)<<6|a[0].charCodeAt(3)&63))}],[/^([\x80-\xFF])/,function(a){R(this.o,a[0])}],[/^\x07/,function(){S(this.o,"bell")}],[/^\x08/,function(){S(this.o,"backspace")}],[/^\x09/,function(){S(this.o,"horizontalTab")}],[/^\x0a/,function(){S(this.o,"lineFeed")}],[/^\x0b/,function(){S(this.o,"verticalTab")}],[/^\x0c/,function(){S(this.o,"formFeed")}],[/^\x0d/,function(){S(this.o,"carriageReturn")}],[/^\x0e/,function(){this.o.H.S=void 0}],[/^\x0f/,function(){this.o.H.S=
void 0}],[/^\x1bF/,function(){}],[/^\x1bG/,function(){}],[/^\x1b\[[Hf]/,function(){P(this.o,1,1)}],[/^\x1b\[([0-9]*)G/,function(a){P(this.o,parseInt(a[1]||"1",10),-1)}],[/^\x1b\[([0-9]*);([0-9]*)[Hf]/,function(a){P(this.o,parseInt(a[2]||"1",10),parseInt(a[1]||"1",10))}],[/^\x1b\[([0-9]*)d/,function(a){P(this.o,1,parseInt(a[1]||"1",10))}],[/^[\x00-\x06]/,function(){}],[/^[\x10-\x1a]/,function(){}],[/^[\x1c-\x1f]/,function(){}],[/^\x1b\[0?K/,function(){Y(this.o,"toEnd")}],[/^\x1b\[1K/,function(){Y(this.o,
"toStart")}],[/^\x1b\[2K/,function(){Y(this.o,"whole")}],[/^\x1bK/,function(){Y(this.o,"toEnd")}],[/^\x1b\[0?J/,function(){wa(this.o,"toEnd")}],[/^\x1b\[1J/,function(){wa(this.o,"toStart")}],[/^\x1b\[2J/,function(){wa(this.o,"whole")}],[/^\x1bJ/,function(){wa(this.o,"toEnd")}],[/^\x1b\[([0-9]*)P/,function(a){va(this.o,parseInt(a[1]||"1",10))}],[/^\x1b\[([0-9]*)X/,function(a){va(this.o,parseInt(a[1]||"1",10))}],[/^\x1b\[([0-9]*)L/,function(a){var b=this.o;a=parseInt(a[1]||"1",10);2<b.A&&b.debug("INSERT_LINES="+
a);if(!(b.cursor.y>b.s.bottom||b.cursor.y<b.s.top)){for(var c=0;c<a;c++){for(var d=b.s.bottom;d>b.cursor.y;d--)ya(b,d-1,d);for(d=0;d<b.width;d++)xa(b,d,b.cursor.y)}for(d=b.cursor.y;d<=b.s.bottom;d++)H(b,d,0,b.width-1)}}],[/^\x1b\[([0-9]*)M/,function(a){var b=this.o;a=parseInt(a[1]||"1",10);2<b.A&&b.debug("DELETE_LINES="+a);if(!(b.cursor.y>b.s.bottom||b.cursor.y<b.s.top)){for(var c=0;c<a;c++){for(var d=b.cursor.y;d<b.s.bottom;d++)ya(b,d+1,d);for(d=0;d<b.width;d++)xa(b,d,b.s.bottom)}for(d=b.cursor.y;d<=
b.s.bottom;d++)H(b,d,0,b.width-1)}}],[/^\x1b\[([0-9])*@/,function(a){var b=this.o;a=parseInt(a[1]||"1",10);2<b.A&&b.debug("INSERT_CHARS="+a);for(var c=0;c<a;c++)sa(b,b.width-1,b.cursor.y),ta(b," ",b.cursor.x,b.cursor.y);H(b,b.cursor.y,b.cursor.x,b.width-1)}],[/^\x1b\[([0-9]+);([0-9]+)r/,function(a){qa(this.o,parseInt(a[1],10),parseInt(a[2],10))}],[/^\x1b\[r/,function(){var a=this.o;2<a.A&&a.debug("RESET_MARGIN=1 "+a.height);qa(a,1,a.height,!0)}],[/^\x1b\[\[([0-9;]*)m/,function(){}],[/^\x1b\[([0-9]*)A/,
function(a){U(this.o,"up",parseInt(a[1]||"1",10))}],[/^\x1b\[([0-9]*)B/,function(a){U(this.o,"down",parseInt(a[1]||"1",10))}],[/^\x1b\[([0-9]*)C/,function(a){U(this.o,"right",parseInt(a[1]||"1",10))}],[/^\x1b\[([0-9]*)D/,function(a){U(this.o,"left",parseInt(a[1]||"1",10))}],[/^\x1b\[([0-9]*)E/,function(a){V(this.o,"nextLine",parseInt(a[1]||"1",10))}],[/^\x1b\[([0-9]*)F/,function(a){V(this.o,"prevLine",parseInt(a[1]||"1",10))}],[/^\x1bA([\x20-\x7F]?)/,function(a){U(this.o,"up",a[1]?a[1].charCodeAt(0)-
32+1:1)}],[/^\x1bB([\x20-\x7F]?)/,function(a){U(this.o,"down",a[1]?a[1].charCodeAt(0)-32+1:1)}],[/^\x1bC([\x20-\x7F]?)/,function(a){U(this.o,"right",a[1]?a[1].charCodeAt(0)-32+1:1)}],[/^\x1bD/,function(){U(this.o,"left",1)}],[/^\x1bY(..)/,function(a){P(this.o,a[1].charCodeAt(1)-32+1,a[1].charCodeAt(0)-32+1)}],[/^\x1bD/,function(){V(this.o,"down",1)}],[/^\x1bM/,function(){V(this.o,"up",1)}],[/^\x1bE/,function(){V(this.o,"nextLine",1)}],[/^\x1b[7]/,function(){Q(this.o,"push",!0)}],[/^\x1b[8]/,function(){Q(this.o,
"pop",!0)}],[/^\x1b\[s/,function(){Q(this.o,"push",!1)}],[/^\x1b\[u/,function(){Q(this.o,"pop",!1)}],[/^\x1b=/,function(){W(this.o,"keypad","cursor")}],[/^\x1b>/,function(){W(this.o,"keypad","numeric")}],[/^\x1b\[(\??)([0-9;]+)h/,function(a){var b=this;a[2].split(";").forEach(function(c){c=a[1]+c;switch(c){case "?1":W(b.o,"cursorKeyANSI",!1);break;case "?3":W(b.o,"width",132);break;case "?4":W(b.o,"scroll","smooth");break;case "?5":W(b.o,"reverseScreen",!0);break;case "?6":W(b.o,"originMode","margin");
break;case "?7":W(b.o,"autoWrap",!0);break;case "?8":W(b.o,"autoRepeat",!0);break;case "?9":W(b.o,"mouseTrackingDown",!0);break;case "?12":W(b.o,"cursorBlink",!0);break;case "?25":W(b.o,"cursor",!0);break;case "?47":W(b.o,"currentScreen",0);break;case "?69":break;case "?1000":W(b.o,"mouseTrackingUp",!0);break;case "?1034":W(b.o,"metaKey",!0);break;case "?1047":W(b.o,"currentScreen",0);break;case "?1048":Q(b.o,"push",!0);break;case "?1049":Q(b.o,"push",!0);W(b.o,"currentScreen",0);Y(b.o,"whole");break;
case "2":W(b.o,"keyboardLocked",!0);break;case "4":W(b.o,"insert",!0);break;case "12":W(b.o,"localEcho",!1);break;case "20":W(b.o,"newLineMode","crlf");break;default:b.debug('Unhandled set mode: "'+c+'"')}})}],[/^\x1b\[(\??)([0-9;]+)l/,function(a){var b=this;a[2].split(";").forEach(function(c){c=a[1]+c;switch(c){case "?1":W(b.o,"cursorKeyANSI",!0);break;case "?2":W(b.o,"vt52",!0);break;case "?3":W(b.o,"width",80);break;case "?4":W(b.o,"scroll","jump");break;case "?5":W(b.o,"reverseScreen",!1);break;
case "?6":W(b.o,"originMode","screen");break;case "?7":W(b.o,"autoWrap",!1);break;case "?8":W(b.o,"autoRepeat",!1);break;case "?9":W(b.o,"mouseTrackingDown",!1);break;case "?12":W(b.o,"cursorBlink",!1);break;case "?25":W(b.o,"cursor",!1);break;case "?47":W(b.o,"currentScreen",1);break;case "?69":break;case "?1000":W(b.o,"mouseTrackingUp",!1);break;case "?1034":W(b.o,"metaKey",!1);break;case "?1047":Y(b.o,"whole");W(b.o,"currentScreen",1);break;case "?1048":Q(b.o,"pop",!0);break;case "?1049":W(b.o,
"currentScreen",1);Q(b.o,"pop",!0);break;case "2":W(b.o,"keyboardLocked",!1);break;case "4":W(b.o,"insert",!1);break;case "12":W(b.o,"localEcho",!0);break;case "20":W(b.o,"newLineMode","cr");break;default:b.debug('Unhandled reset mode: "'+c+'"')}})}],[/^\x1b\[\?([0-9;]*)c/,function(a){this.debug("cursor layout"+a[1])}],[/^\x1bH/,function(){P(this.o,1,1)}],[/^\x1b\[0?g/,function(){Z(this.o,"tabStop","remove")}],[/^\x1b\[3g/,function(){Z(this.o,"tabStop","clear")}],[/^\x1b#3/,function(){za(this.o,"dwdhTopHalf")}],
[/^\x1b#4/,function(){za(this.o,"dwdhBottomHalf")}],[/^\x1b#5/,function(){za(this.o,"swsh")}],[/^\x1b#6/,function(){za(this.o,"dwsh")}],[/^\x1b\[!p/,function(){Z(this.o,"softReset",void 0)}],[/^\x1bc/,function(){Z(this.o,"reset",void 0)}],[/^\x1b\[([0-9;]*)t/,function(){}],[/^\x1b\]2;([^\x1b\x07]*)\x07/,function(a){var b=this.o;a=a[1];2<b.A&&b.debug("SET_WINDOW_TITLE= "+a);b.pa=a;J(b,{title:a})}],[/^\x1b\]1;([^\x1b\x07]*)\x07/,function(a){var b=this.o;a=a[1];2<b.A&&b.debug("SET_ICON_TITLE= "+a);b.ka=
a;J(b,{icon:a})}],[/^\x1b\]0;([^\x1b\x07]*)\x07/,function(a){var b=this.o;a=a[1];2<b.A&&b.debug("SET_TITLE= "+a);b.pa=a;b.ka=a;J(b,{title:a,icon:a})}],[/^\x1b\$?([()*+-./])([ABCEHKQRYZ0124567=])/,function(a){var b=a[1];a=a[2];switch(b){case ")":b="g0";break;case "(":b="g1";break;case "*":b="g2";break;case "+":b="g3"}switch(a){case "A":a="uk";break;case "B":a="us";break;case "0":a="line";break;case "1":a="rom";break;case "2":a="romSpecial"}this.o.H[b]=a}],[/^\x1bN(a|[^a])/,function(a){Z(this.o,"g2char",
a[1])}],[/^\x1bO(a|[^a])/,function(a){Z(this.o,"g3char",a[1])}],[/^\x1b([0-9;?]*)n/,function(){}],[/^\x1b(\[0?c|Z)/,function(){}],[/^\x1b\[>c/,function(){}],[/^\x1b\[([0-9;]*)q/,function(a){var b=this;(a[1].length?a[1]:"0").split(";").forEach(function(a){a=parseInt(a,10);0==a?Z(b.o,"led","off"):Z(b.o,"led","on")})}],[/^\x1b\[[145]?i/,function(){}],[/^\x1b\[([0-9;]*)y/,function(){Z(this.o,"hardware","selfTestRaw")}],[/^\x1b#8/,function(){Z(this.o,"hardware","screenAlignment")}],[/^\x1b%@/,function(){}],
[/^\x1b%G/,function(){}],[/^\x1b\[9;([0-9]+)\]/,function(){}],[/^\x1b\[([0-9]+)(;[0-9]+)?\xb0/,function(a){W(this.o,"borderColor",[a[1],a[2]?a[2].substr(1):null])}]];
// Input 10
function F(a,b){var c=this;b.name=b.name;b.title=b.title;b.font=b.font;b.fontsize=b.fontsize;b.Ab=b.fontfamily;b.P=b.boldfont;b.Ya=b.scan;b.Fa=b.warp;b.loop=b.loop;b.qb=b.autostart;b.Ob=b.onready;b.debug=b.debug;b.Q=b.callback;b.Aa=b.onupdate;b.Lb=b.oncompletion;b.Kb=b.onbookmark;b.Mb=b.onpause;b.Nb=b.onplay;b.Ib=b.noskip;c.xb=function(a){if(c.options.debug)if(c.J&&c.J[c.O]){var d=new Date(1E3*(c.J[c.O].time-c.J[0].time));b.debug(("0"+d.getUTCHours()).slice(-2)+":"+("0"+d.getUTCMinutes()).slice(-2)+
":"+("0"+d.getUTCSeconds()).slice(-2)+" "+a)}else b.debug("--:--:-- "+a)};c.debug=function(a){c.xb("player.js: "+a)};c.options=b;c.options.Fa||(c.options.Fa=1);var d=b.name||"index.rec",e=new XMLHttpRequest;e.open("GET",d,!0);e.setRequestHeader("Cache-Control","no-cache");e.setRequestHeader("If-Match","*");e.overrideMimeType("application/octet-stream; charset=x-user-defined");e.onload=function(){if(200!=e.status){if(alert("ERROR[0] - HTTP request '"+d+"': "+e.statusText+" ["+e.status+"]"),b.onclose)b.onclose()}else{var f=
e.responseText;if(-1==f.search(/[^\x0a\x0dABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=]/)){var k=f.replace(/[\x0A\x0C]/g,""),g=y.ja.bb.parse(k);y.ja.eb.stringify(g);1398893684==g.G[0]&&1701076831==g.G[1]&&(g=prompt("Please enter a passphrase to decrypt the stream: "))&&(f=y.$a.ia(k,g).toString(y.ja.eb))}try{c.J=new na(f),c.Za=c.J[c.J.length-1].time-c.J[0].time}catch(h){alert(h);if(c.options.onclose)c.options.onclose();return}c.debug("GO");for(var r,s,f="",k=0;k<c.J.length;k++){f+=
c.J[k].data;for(g=RegExp("\u001b\\[[8];([0-9]+);([0-9]+)t","g");;){g=g.exec(f);if(!g)break;c.debug("Found[1]: "+g[1]+"/"+g[2]);r=parseInt(g[2],10);s=parseInt(g[1],10);break}if(!r&&!s)for(var u=RegExp("\u001b\\[([0-9]+);([0-9]+)r","g");;){g=u.exec(f);if(!g)break;var q=parseInt(g[2],10);if(!s||q>s)c.debug("Found[0]: "+g[1]+"/"+q),s=q}f=f.substr(-12)}c.debug("OK ["+r+"x"+s+"]");f=B(b);f.la=function(){Da(c)};f.Q=b.Q||function(){};f.debug=function(a){c.xb(a)};f.width=r||80;f.height=s||24;f.Y=!0;c.X=new ia(a,
f)}};e.send(null);return this}function Da(a){if(a.X)a.Bb={va:ma(a.X),index:0},a.options.Ob&&a.options.Ob(new Date(1E3*a.Za)),0<a.options.qb&&(b=a,setTimeout(function(){b.start()},parseInt(a.options.qb,10)));else{var b=a;setTimeout(function(){Da(b)},10)}}v=F.prototype;v.start=function(a){var b=(new Date).getTime()/1E3;a=a||0;this.oa=!0;this.startTime=b;this.pc=this.J[a].time;this.O=a;this.timeout=null;Ea(this);this.options.Nb&&this.options.Nb()};
function Ea(a){for(var b=(new Date).getTime()/1E3;!a.action&&a.O<a.J.length&&(a.J[a.O].time-a.pc<(b-a.startTime)*a.options.Fa||a.options.Ya);){a.X.na.parse(a.J[a.O++].data);if(a.options.Ib)break;if(a.options.Ya&&1<(new Date).getTime()/1E3-b)break}var c=a.options.Ib&&!a.options.Ya||a.action||a.O==a.J.length,b=(new Date).getTime();if(19<b-a.Qb||c||!a.Qb)a.Qb=b,la(a.X);if(!a.action||a.action(!0))if(a.O<a.J.length){a.options.Aa&&(b=a.J[a.O].time-a.J[0].time,c=new Date(1E3*b),a.options.Aa(c,b/a.Za));var d=
a;setTimeout(function(){Ea(d)},0)}else a.options.loop?(d=a,a.X.Ea(a.Bb),setTimeout(function(){d.start(0)},a.options.loop)):(a.timeout=null,a.oa=!1,a.options.Aa&&(c=new Date(1E3*a.Za),a.options.Aa(c,1)),a.options.Lb&&a.options.Lb(),c=new Date((new Date).getTime()-1E3*a.startTime),a.debug("Completed ["+("0"+c.getUTCHours()).slice(-2)+":"+("0"+c.getUTCMinutes()).slice(-2)+":"+("0"+c.getUTCSeconds()).slice(-2)+"]"))}
v.Ua=function(){if(this.oa){var a=this;this.action=function(){a.action=null;a.oa=!1;this.options.Mb&&this.options.Mb();return!1};return!1}this.O==this.J.length?this.Wa():this.start(this.O)};v.Sb=function(){var a=this;this.action=function(){a.action=null;a.va={va:ma(a.X),index:a.O};this.options.Kb&&this.options.Kb();return!0};this.oa||this.action(!1);return!1};
v.Va=function(a){if(a){var b=this;this.action=function(c){b.action=null;b.X.Ea(a.va);la(b.X);(c||0==a.index)&&setTimeout(function(){b.start(a.index)},1);return!1};this.oa||this.action(!1)}};v.Ra=function(){this.Va(this.va);return!1};v.Wa=function(){this.Va(this.Bb);return!1};v.Ac=function(a){this.options.Fa=a;return!1};window.TTVPlayer=F;F.prototype.rewind=F.prototype.Wa;F.prototype.playpause=F.prototype.Ua;F.prototype.setBookmark=F.prototype.Sb;F.prototype.resume=F.prototype.Va;
F.prototype.jump=F.prototype.Ra;F.prototype.setWarpFactor=F.prototype.Ac;
